"use client";

import * as React from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import {
  Bot,
  CalendarClock,
  CornerDownLeft,
  Map as MapIcon,
  MessagesSquare,
  Network,
  RefreshCw,
  Send,
  Sparkles,
  Target,
} from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Markdown } from "@/components/ui/markdown";
import { Tabs } from "@/components/ui/tabs";
import {
  aiDailyPlan,
  aiPlanner,
  aiSdReview,
  aiWeaknessDetect,
  askCoach,
  type AIResponse,
  type WeaknessDetectResponse,
} from "@/lib/api/ai";
import { listDesignProblems, type DesignProblem } from "@/lib/api/content";
import { pillarLabel } from "@/lib/pillar-meta";

type TabValue = "daily-plan" | "planner" | "coach" | "weakness" | "sd-review";

const TABS = [
  { value: "daily-plan" as const, label: "Daily Plan", icon: CalendarClock },
  { value: "planner" as const, label: "Study Planner", icon: MapIcon },
  { value: "coach" as const, label: "Interview Coach", icon: MessagesSquare },
  { value: "weakness" as const, label: "Weakness Detector", icon: Target },
  { value: "sd-review" as const, label: "System Design Review", icon: Network },
];

export default function AICoachPage() {
  const [tab, setTab] = React.useState<TabValue>("daily-plan");

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-h1">AI Coach</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Your AI study companion — daily plans, coaching, and reviews. When the model is
          unavailable, you still get a deterministic, heuristic answer.
        </p>
      </header>

      <Tabs
        ariaLabel="AI assistants"
        value={tab}
        onValueChange={(v) => setTab(v as TabValue)}
        tabs={TABS.map((t) => ({
          value: t.value,
          label: (
            <span className="flex items-center gap-1.5">
              <t.icon className="size-4" aria-hidden /> {t.label}
            </span>
          ),
        }))}
      />

      <div role="tabpanel">
        {tab === "daily-plan" && <DailyPlanPanel />}
        {tab === "planner" && <PlannerPanel />}
        {tab === "coach" && <CoachPanel />}
        {tab === "weakness" && <WeaknessPanel />}
        {tab === "sd-review" && <SdReviewPanel />}
      </div>
    </div>
  );
}

/** Subtle "AI" vs "heuristic" provenance badge driven by `used_fallback`. */
function ProvenanceBadge({ usedFallback }: { usedFallback?: boolean }) {
  if (usedFallback) {
    return (
      <Badge variant="secondary" size="sm" title="Generated by a deterministic heuristic">
        Heuristic
      </Badge>
    );
  }
  return (
    <Badge variant="info" size="sm" title="Generated by the AI model">
      <Sparkles className="size-3" aria-hidden /> AI
    </Badge>
  );
}

function ResponseCard({
  title,
  response,
}: {
  title: string;
  response: AIResponse;
}) {
  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between gap-2 space-y-0">
        <CardTitle className="text-base">{title}</CardTitle>
        <ProvenanceBadge usedFallback={response.used_fallback} />
      </CardHeader>
      <CardContent>
        <Markdown content={response.content || "_No content returned._"} />
      </CardContent>
    </Card>
  );
}

function ErrorAlert({ onRetry }: { onRetry: () => void }) {
  return (
    <Alert variant="danger" title="The assistant couldn't respond">
      The AI service may be busy or unavailable. Try again.
      <div className="mt-3">
        <Button variant="outline" size="sm" onClick={onRetry}>
          <RefreshCw aria-hidden /> Retry
        </Button>
      </div>
    </Alert>
  );
}

function GeneratingSkeleton() {
  return (
    <Card>
      <CardContent className="space-y-2 py-5" aria-busy>
        <span className="sr-only" role="status">
          Generating…
        </span>
        <Skeleton className="h-4 w-1/3" />
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-5/6" />
        <Skeleton className="h-4 w-2/3" />
      </CardContent>
    </Card>
  );
}

/* ---- Daily Plan ---- */

function DailyPlanPanel() {
  const mutation = useMutation({ mutationFn: () => aiDailyPlan({}) });

  return (
    <div className="space-y-4">
      <Card>
        <CardContent className="flex flex-col items-start gap-3 py-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-h3 font-semibold">Refine today&apos;s plan</h2>
            <p className="mt-0.5 text-sm text-muted-foreground">
              Get an AI-refined daily plan based on your roadmap, revision, and recent progress.
            </p>
          </div>
          <Button onClick={() => mutation.mutate()} loading={mutation.isPending}>
            <Sparkles aria-hidden /> Generate plan
          </Button>
        </CardContent>
      </Card>

      {mutation.isPending && <GeneratingSkeleton />}
      {mutation.isError && <ErrorAlert onRetry={() => mutation.mutate()} />}
      {mutation.data && <ResponseCard title="Today's refined plan" response={mutation.data} />}
    </div>
  );
}

/* ---- Study Planner ---- */

function PlannerPanel() {
  const [notes, setNotes] = React.useState("");
  const mutation = useMutation({
    mutationFn: () => aiPlanner({ notes: notes.trim() || undefined }),
  });

  return (
    <div className="space-y-4">
      <Card>
        <CardContent className="space-y-3 py-5">
          <div>
            <h2 className="text-h3 font-semibold">Study planner</h2>
            <p className="mt-0.5 text-sm text-muted-foreground">
              Ask the planner to refine your roadmap. Add any constraints or focus areas.
            </p>
          </div>
          <Textarea
            aria-label="Planning notes"
            rows={3}
            placeholder="e.g. I have 2 weeks, want to prioritize system design and graphs…"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
          />
          <div className="flex justify-end">
            <Button onClick={() => mutation.mutate()} loading={mutation.isPending}>
              <Sparkles aria-hidden /> Get suggestions
            </Button>
          </div>
        </CardContent>
      </Card>

      {mutation.isPending && <GeneratingSkeleton />}
      {mutation.isError && <ErrorAlert onRetry={() => mutation.mutate()} />}
      {mutation.data && <ResponseCard title="Planner suggestions" response={mutation.data} />}
    </div>
  );
}

/* ---- Interview Coach (chat) ---- */

interface ChatTurn {
  id: number;
  role: "user" | "assistant";
  content: string;
  usedFallback?: boolean;
}

function CoachPanel() {
  const [input, setInput] = React.useState("");
  const [turns, setTurns] = React.useState<ChatTurn[]>([]);
  const nextId = React.useRef(0);
  const endRef = React.useRef<HTMLDivElement>(null);

  const mutation = useMutation({
    mutationFn: (message: string) => askCoach(message),
    onSuccess: (res) => {
      setTurns((t) => [
        ...t,
        {
          id: nextId.current++,
          role: "assistant",
          content: res.content,
          usedFallback: res.used_fallback,
        },
      ]);
    },
  });

  React.useEffect(() => {
    endRef.current?.scrollIntoView({ block: "nearest" });
  }, [turns, mutation.isPending]);

  function send() {
    const message = input.trim();
    if (!message || mutation.isPending) return;
    setTurns((t) => [...t, { id: nextId.current++, role: "user", content: message }]);
    setInput("");
    mutation.mutate(message);
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Interview coach</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div
          className="max-h-[28rem] space-y-3 overflow-y-auto"
          role="log"
          aria-live="polite"
          aria-label="Conversation with the AI coach"
        >
          {turns.length === 0 && !mutation.isPending && (
            <div className="flex flex-col items-center gap-2 py-10 text-center text-sm text-muted-foreground">
              <Bot className="size-8" aria-hidden />
              <p>Ask anything — &ldquo;How do I approach a system design round?&rdquo;</p>
            </div>
          )}
          {turns.map((turn) =>
            turn.role === "user" ? (
              <div key={turn.id} className="flex justify-end">
                <p className="max-w-[85%] rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">
                  {turn.content}
                </p>
              </div>
            ) : (
              <div key={turn.id} className="flex flex-col gap-1">
                <div className="flex items-center gap-1.5">
                  <Bot className="size-3.5 text-muted-foreground" aria-hidden />
                  <span className="text-2xs uppercase text-muted-foreground">Coach</span>
                  <ProvenanceBadge usedFallback={turn.usedFallback} />
                </div>
                <div className="rounded-lg bg-muted/50 px-3 py-2">
                  <Markdown content={turn.content || "_No response._"} />
                </div>
              </div>
            ),
          )}
          {mutation.isPending && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground" role="status">
              <Bot className="size-3.5" aria-hidden /> Coach is thinking…
            </div>
          )}
          {mutation.isError && (
            <p className="text-sm text-danger" role="alert">
              Couldn&apos;t reach the coach. Try sending again.
            </p>
          )}
          <div ref={endRef} />
        </div>

        <form
          className="flex items-end gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            send();
          }}
        >
          <Textarea
            aria-label="Message the coach"
            rows={1}
            placeholder="Ask the coach…"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                send();
              }
            }}
            className="min-h-9 resize-none"
          />
          <Button type="submit" loading={mutation.isPending} disabled={!input.trim()}>
            {!mutation.isPending && <Send aria-hidden />} Send
          </Button>
        </form>
        <p className="flex items-center gap-1 text-2xs text-muted-foreground">
          <CornerDownLeft className="size-3" aria-hidden /> Enter to send · Shift+Enter for a new line
        </p>
      </CardContent>
    </Card>
  );
}

/* ---- Weakness Detector ---- */

function WeaknessPanel() {
  const mutation = useMutation<WeaknessDetectResponse, unknown, void>({
    mutationFn: () => aiWeaknessDetect(),
  });

  const data = mutation.data;
  const weak = data?.weak_topics ?? [];
  const tasks = data?.recommended_tasks ?? [];

  return (
    <div className="space-y-4">
      <Card>
        <CardContent className="flex flex-col items-start gap-3 py-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-h3 font-semibold">Detect weaknesses</h2>
            <p className="mt-0.5 text-sm text-muted-foreground">
              Analyze your progress and mocks to surface the topics holding you back.
            </p>
          </div>
          <Button onClick={() => mutation.mutate()} loading={mutation.isPending}>
            <Target aria-hidden /> Analyze
          </Button>
        </CardContent>
      </Card>

      {mutation.isPending && <GeneratingSkeleton />}
      {mutation.isError && <ErrorAlert onRetry={() => mutation.mutate()} />}

      {data && (
        <>
          <Card>
            <CardHeader className="flex-row items-center justify-between gap-2 space-y-0">
              <CardTitle className="text-base">Weakest topics</CardTitle>
              <ProvenanceBadge usedFallback={data.used_fallback} />
            </CardHeader>
            <CardContent>
              {weak.length === 0 ? (
                <p className="text-sm text-muted-foreground">
                  No clear weak spots detected — keep going.
                </p>
              ) : (
                <ul className="space-y-2">
                  {weak.map((t) => (
                    <li
                      key={t.topic_id}
                      className="flex items-center justify-between gap-3 rounded-md border border-border px-3 py-2"
                    >
                      <span className="min-w-0 flex-1 truncate text-sm font-medium">
                        {t.topic_name}
                      </span>
                      <Badge variant="outline" size="sm">
                        {pillarLabel(t.pillar_type)}
                      </Badge>
                      {typeof t.completion_pct === "number" && (
                        <span className="text-xs tabular-nums text-muted-foreground">
                          {Math.round(t.completion_pct)}% done
                        </span>
                      )}
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>

          {tasks.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Recommended next steps</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="list-disc space-y-1 pl-5 text-sm text-foreground/90 marker:text-muted-foreground">
                  {tasks.map((task, i) => (
                    <li key={i}>{task}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}

/* ---- System Design Review ---- */

function SdReviewPanel() {
  const [designProblemId, setDesignProblemId] = React.useState("");
  const [answer, setAnswer] = React.useState("");

  const problemsQuery = useQuery({
    queryKey: ["design-problems", "ai-sd-review"],
    queryFn: () => listDesignProblems({ page_size: 100 }),
  });

  const mutation = useMutation({
    mutationFn: () => aiSdReview({ design_problem_id: designProblemId, answer_md: answer }),
  });

  const problems: DesignProblem[] = problemsQuery.data?.data ?? [];
  const canSubmit = Boolean(designProblemId) && answer.trim().length > 0;

  return (
    <div className="space-y-4">
      <Card>
        <CardContent className="space-y-3 py-5">
          <div>
            <h2 className="text-h3 font-semibold">System design review</h2>
            <p className="mt-0.5 text-sm text-muted-foreground">
              Pick a design problem, paste your answer, and get a structured critique.
            </p>
          </div>

          <div className="space-y-1.5">
            <label htmlFor="sd-problem" className="text-sm font-medium">
              Design problem
            </label>
            <Select
              id="sd-problem"
              value={designProblemId}
              disabled={problemsQuery.isLoading}
              onChange={(e) => setDesignProblemId(e.target.value)}
            >
              <option value="">
                {problemsQuery.isLoading ? "Loading…" : "Select a design problem…"}
              </option>
              {problems.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.title}
                </option>
              ))}
            </Select>
          </div>

          <div className="space-y-1.5">
            <label htmlFor="sd-answer" className="text-sm font-medium">
              Your answer (Markdown)
            </label>
            <Textarea
              id="sd-answer"
              rows={10}
              placeholder="Paste your system-design write-up here — requirements, capacity, API, data model, scaling, trade-offs…"
              value={answer}
              onChange={(e) => setAnswer(e.target.value)}
            />
          </div>

          <div className="flex justify-end">
            <Button onClick={() => mutation.mutate()} loading={mutation.isPending} disabled={!canSubmit}>
              <Network aria-hidden /> Review my answer
            </Button>
          </div>
        </CardContent>
      </Card>

      {mutation.isPending && <GeneratingSkeleton />}
      {mutation.isError && <ErrorAlert onRetry={() => mutation.mutate()} />}
      {mutation.data && <ResponseCard title="Design review" response={mutation.data} />}
    </div>
  );
}
